-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 09:20:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Autor` (
  `cod_autor` INT NOT NULL AUTO_INCREMENT,
  `nome_autor` VARCHAR(25) NOT NULL,
  `dat_nasc_autor` DATETIME NULL,
  PRIMARY KEY (`cod_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Livro` (
  `cod_livro` INT NOT NULL AUTO_INCREMENT,
  `titulo_livro` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_livro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Autor_Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Autor_Livro` (
  `cod_autor` INT NOT NULL,
  `cod_livro` INT NOT NULL,
  PRIMARY KEY (`cod_autor`, `cod_livro`),
  INDEX `fk_Autor_has_Livro_Livro1_idx` (`cod_livro` ASC),
  INDEX `fk_Autor_has_Livro_Autor_idx` (`cod_autor` ASC),
  CONSTRAINT `fk_Autor_has_Livro_Autor`
    FOREIGN KEY (`cod_autor`)
    REFERENCES `testdb`.`Autor` (`cod_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Livro_Livro1`
    FOREIGN KEY (`cod_livro`)
    REFERENCES `testdb`.`Livro` (`cod_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Usuario` (
  `cod_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(15) NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `senha` CHAR(8) NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`cod_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
