/*
 * Tela principal do sistema para gerenciamento de uma biblioteca.
 */
package biblio.ui;

import biblio.control.Main;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import javax.swing.JDialog;
import java.awt.event.WindowEvent;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author leonardosilva
 */
public class BibliotecaUI extends javax.swing.JFrame {
    /**
     * Creates new form BibliotecaUI
     */
    public BibliotecaUI() {
        initComponents();
        // Abre tela de login
        JDialog login = new DlgLogin(this, true);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        // Se login foi validado, entao abre tela principal
        if (Main.getUserLogin().isEmpty()) {
           this.closeFrame(); 
        } else {
           lblActiveUser.setText(lblActiveUser.getText()+Main.getUserLogin());
        }
    }
    
    private void closeFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlBkgImage = new javax.swing.JPanel();
        tfTeste = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblActiveUser = new javax.swing.JLabel();
        lblBkgImage = new javax.swing.JLabel();
        mnbMainMenu = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        mniAutor = new javax.swing.JMenuItem();
        mniLivro = new javax.swing.JMenuItem();
        mniCliente = new javax.swing.JMenuItem();
        mnMovimentacao = new javax.swing.JMenu();
        mniEmprestimo = new javax.swing.JMenuItem();
        mniDevolucao = new javax.swing.JMenuItem();
        mniReserva = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mniRelEmpPorCliente = new javax.swing.JMenuItem();
        mniRelReservasPorPeriodo = new javax.swing.JMenuItem();
        mnConfiguracao = new javax.swing.JMenu();
        mnJanelas = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento da Biblioteca");
        setResizable(false);

        pnlBkgImage.setLayout(null);

        tfTeste.setText("jTextField1");
        pnlBkgImage.add(tfTeste);
        tfTeste.setBounds(210, 50, 210, 28);

        lblActiveUser.setText("Usuário: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblActiveUser)
                .addGap(243, 243, 243))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblActiveUser))
        );

        lblBkgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/ui/BackgroundImage.jpg"))); // NOI18N

        mnCadastro.setText("Cadastro");
        mnCadastro.setToolTipText("");

        mniAutor.setText("Autor");
        mniAutor.setToolTipText("");
        mniAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAutorActionPerformed(evt);
            }
        });
        mnCadastro.add(mniAutor);

        mniLivro.setText("Livro");
        mniLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLivroActionPerformed(evt);
            }
        });
        mnCadastro.add(mniLivro);

        mniCliente.setText("Cliente");
        mniCliente.setToolTipText("");
        mnCadastro.add(mniCliente);

        mnbMainMenu.add(mnCadastro);

        mnMovimentacao.setText("Movimentação");
        mnMovimentacao.setToolTipText("");

        mniEmprestimo.setText("Empréstimo");
        mniEmprestimo.setToolTipText("");
        mnMovimentacao.add(mniEmprestimo);

        mniDevolucao.setText("Devolução");
        mniDevolucao.setToolTipText("");
        mnMovimentacao.add(mniDevolucao);

        mniReserva.setText("Reserva");
        mniReserva.setToolTipText("");
        mnMovimentacao.add(mniReserva);

        mnbMainMenu.add(mnMovimentacao);

        mnRelatorio.setText("Relatório");
        mnRelatorio.setToolTipText("");

        mniRelEmpPorCliente.setText("Empréstimos por Cliente");
        mniRelEmpPorCliente.setToolTipText("");
        mnRelatorio.add(mniRelEmpPorCliente);

        mniRelReservasPorPeriodo.setText("Reservas por Período");
        mniRelReservasPorPeriodo.setToolTipText("");
        mnRelatorio.add(mniRelReservasPorPeriodo);

        mnbMainMenu.add(mnRelatorio);

        mnConfiguracao.setText("Configuração");
        mnConfiguracao.setToolTipText("");
        mnbMainMenu.add(mnConfiguracao);

        mnJanelas.setText("Janelas");
        mnJanelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnJanelasMouseClicked(evt);
            }
        });
        mnJanelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJanelasActionPerformed(evt);
            }
        });
        mnbMainMenu.add(mnJanelas);

        mnSobre.setText("Sobre");
        mnSobre.setToolTipText("");
        mnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSobreMouseClicked(evt);
            }
        });
        mnbMainMenu.add(mnSobre);

        mnSair.setText("Sair");
        mnSair.setToolTipText("");
        mnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSairMouseClicked(evt);
            }
        });
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        mnbMainMenu.add(mnSair);

        setJMenuBar(mnbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblBkgImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBkgImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlBkgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBkgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed

    }//GEN-LAST:event_mnSairActionPerformed

    private void mnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSairMouseClicked
        this.closeFrame();
    }//GEN-LAST:event_mnSairMouseClicked

    private void mniAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAutorActionPerformed
        JFrame frame = new FrmAutor();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);        
    }//GEN-LAST:event_mniAutorActionPerformed

    private void mnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSobreMouseClicked

    }//GEN-LAST:event_mnSobreMouseClicked

    private void mnJanelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJanelasActionPerformed

    }//GEN-LAST:event_mnJanelasActionPerformed

    private void mnJanelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnJanelasMouseClicked
        mnJanelas.removeAll();
        for (Frame frame : Frame.getFrames()) {
            mnJanelas.add(new JMenuItem(new AbstractAction(frame.getTitle()) {
                @Override
                public void actionPerformed(ActionEvent e) {
                    frame.requestFocus();        
                }
            }));
        }
    }//GEN-LAST:event_mnJanelasMouseClicked

    private void mniLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLivroActionPerformed
        JFrame frame = new FrmLivro();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);        
    }//GEN-LAST:event_mniLivroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActiveUser;
    private javax.swing.JLabel lblBkgImage;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnConfiguracao;
    private javax.swing.JMenu mnJanelas;
    private javax.swing.JMenu mnMovimentacao;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenu mnSobre;
    private javax.swing.JMenuBar mnbMainMenu;
    private javax.swing.JMenuItem mniAutor;
    private javax.swing.JMenuItem mniCliente;
    private javax.swing.JMenuItem mniDevolucao;
    private javax.swing.JMenuItem mniEmprestimo;
    private javax.swing.JMenuItem mniLivro;
    private javax.swing.JMenuItem mniRelEmpPorCliente;
    private javax.swing.JMenuItem mniRelReservasPorPeriodo;
    private javax.swing.JMenuItem mniReserva;
    private javax.swing.JPanel pnlBkgImage;
    private javax.swing.JTextField tfTeste;
    // End of variables declaration//GEN-END:variables
}
